package.json
src/app.js
src/lib/config.js
src/lib/settings.js
src/lib/settings.test.js
test/mocks/mappings/fraud.json
yarn.lock

- use v0.0.9 of common-express
- add required config variables
- update mocks to separate fraud check call from authorization call
`kbv-front` has had a few updates with respect to the `oauth` flow - this PR brings `fraud-front` into alignment with these changes

feat: Align fraud-front CRI with kbv

---

Dockerfile

Added Dockerfile that builds Fraud frontend image
Please see above
To facilitate fraud build into Fargate
- [KBV-447](https://govukverify.atlassian.net/browse/KBV-447)
- [KBV-454](https://govukverify.atlassian.net/browse/KBV-454)

Create a Dockerfile that builds Fraud frontend image

---

deploy/template.yaml

frontend instances should scale when there is high traffic load
Add autoscaling for production environment
Currently this will only scale to a max of 3 containers.
Performance scaling required in production.

ECS: add ecs autoscaling for production

---

deploy/template.yaml

Use redis for session caching on frontend
Initially this provides a cluster with 2 nodes, running multi-az. 
No performance scaling implemented at present.
Create redis cache and preset the frontend env var REDIS_SESSION_URL
Required for session caching
- [KBV-514](https://govukverify.atlassian.net/browse/KBV-514)
- REDIS_SESSION_URL presented to frontend.

KBV-514: Add redis cluster

---

deploy/template.yaml
package.json
src/app.js
src/lib/config.js
yarn.lock

Updated fraud front to use express-session and dynamodb-connect to store the front-end session details within an aws DynamoDB table.
To have persistant storage method for the front-end data that is in line with the rest of the programme and means we can avoid setting up and managing a Redis cluster as the alternative.
- [KBV-609](https://govukverify.atlassian.net/browse/KBV-609)

Update fraud-front to connect to DynamoDB for its session storage

---

src/app.js

- Changed default `i18next` cookie property to `lng` to match [auth team's usage](https://github.com/alphagov/di-authentication-frontend/blob/11bf1617e25e925ab680096f813f9c0d4876792c/src/config/i18next.ts#L8-L11).
- Added allowedLang
- Added fallbackLang
Aligning the cookies means that when the auth team set a preference for a language, that it is applied in the KBV UI as well.
- [OJ-876](https://govukverify.atlassian.net/browse/OJ-876)

feat: Add config for English and Welsh translations

---

deploy/template.yaml

- Modified the API_BASE_URL environment variable to refer to the new fraud CRI stack
- To migrate to the new common stack framework
- [OJ-988](https://govukverify.atlassian.net/browse/OJ-988)

OJ-988 - Refer to fraud-api v1

---

deploy/template.yaml

Removed old prod log subscription
Because the old endpoint is being decommissioned

Removing-CSLS-Rust: Removing old log subscriptions

---

.secrets.baseline
deploy/template.yaml

Added alerts for low and absent task counts and 500 errors
So that we know if the frontend is experiencing any issues

LIME-191: Adding basic alerting for fraud frontend

---

deploy/template.yaml

Added ok state to alerts
So that alerts can be removed when the service has stabilised

LIME-191: Added Ok state to frontend alerts

---

package.json

Common-express version reference
In order to Send a users ip_address to TXMA in logs

LIME-252 - Updating common-expresss version reference

---

package.json
src/locales/cy/default.yml
src/locales/en/default.yml
yarn.lock

Update common-express to v1.0.0
Update dependancies to versions used by common-express v1.0.0
- i18next-http-middleware@3.3.0
- i18next@22.4.14
common-express v1.0.0 contains a fix for missing localisation text when accepting/rejecting the cookie banner
- [LIME-665](https://govukverify.atlassian.net/browse/LIME-665)
- [LIME-633](https://govukverify.atlassian.net/browse/LIME-633)
- [common-express v1.0.0](https://github.com/alphagov/di-ipv-cri-common-express/releases/tag/v1.0.0)
[LIME-665]: https://govukverify.atlassian.net/browse/LIME-665?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIME-633]: https://govukverify.atlassian.net/browse/LIME-633?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-633 Fix cookie banner localisation and update common-express to bring in cookie banner localisation fix

---

src/locales/cy/default.yml
src/locales/cy/pages.errors.yml
src/locales/en/default.yml
src/locales/en/pages.errors.yml
test/browser/features/fraud.feature
test/browser/pages/check.js
test/browser/step_definitions/fraud.js

The support link has been changed to the new one-login version.
Due to contact centre being onboarded to one-login.
- [LIME-834](https://govukverify.atlassian.net/browse/LIME-834)
[LIME-834]: https://govukverify.atlassian.net/browse/LIME-834?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-834 updating support link to one-login

---

src/locales/cy/default.yml
src/locales/cy/pages.yml
src/locales/en/default.yml
src/locales/en/pages.yml
src/views/errors/error.html
src/views/errors/page-not-found.html
src/views/errors/session-ended.html
test/browser/pages/error.js

Updated Fraud CRI to align with other LIME CRIs
Added custom error pages to overwrite common express
Updated locales files
To align with the other LIME CRIs
and to ensure error page content could be updated

LIME-834: Overriding common express error pages

---

deploy/template.yaml
package.json
src/app.js
src/lib/config.js

Added config to set the log level to warn and debug in the lower environments
To ensure log levels are always correctly set in the higher environments for hmpo-app and common express

LIME-868: Setting log level to warn by default and debug for dev runs

---

package.json
src/app.js
yarn.lock

Switch to the @govuk-one-login/di-ipv-cri-common-express NPM package 
common-express updated to version 5.0.0, 
govuk-frontend updated to 4.7.0
Git releases are being deprecated in favor of the NPM releases
common-express updated to prepare for 5.x release
govuk-frontend update in preparation of switch to 4.8 release
- [LIME-1014](https://govukverify.atlassian.net/browse/LIME-1014)
[LIME-1014]: https://govukverify.atlassian.net/browse/LIME-1014?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1014 Switch to common-express NPM package and update to version 5.0.0, govuk-frontend updated to 4.7.0

---

src/views/fraud/check.html

- Navigation tracker data layer push was firing with URL, Link Domain and Link Path Parts all undefined. So I added data-link attribute which the tracker uses to populate the url parameter.
- Updated Package to latest version.
Fix Bug 
- [DFC-454](https://govukverify.atlassian.net/browse/DFC-454)
[DFC-454]: https://govukverify.atlassian.net/browse/DFC-454?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GA4 Implementation Bug Fix | Inbound Button not populating URL

---

deploy/template.yaml
package.json
src/app/fraud/controllers/check.js
test/browser/support/setup.js
yarn.lock

A new version of common-express has been introduced, so we can pass through headers for cloudfront correctly.
- [LIME-1127](https://govukverify.atlassian.net/browse/LIME-1127)
[LIME-1127]: https://govukverify.atlassian.net/browse/LIME-1127?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1127 changes to headers for cloudfront

---

deploy/template.yaml

IPS-741 Lime CloudFront Link
Enabled CloudFront Distribution WAF Link in all environments inc Prod
- CloudFront WAF Link is in count mode in prod right now, this enables the actual WAF link in blocking mode in all envs.
modified:   deploy/template.yaml
- [IPS-741](https://govukverify.atlassian.net/browse/IPS-741)
[IPS-741]: https://govukverify.atlassian.net/browse/IPS-741?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IPS-741 Lime CloudFront Link

---

deploy/template.yaml

Stage 1 of 2 for enabling ECS Canaries (Stage 2 is [here]()
Added the ECSCanaryDeployment nested Stack to handle Blue/Green ECS deployments
Assumption made that we will always want to have Canary infrastructure in place (even if deployment strategy is AllAtOnce)
Canary deployments provide extra safety measures when rolling out new application image versions
https://govukverify.atlassian.net/browse/IPS-556

IPS-556: ecs canary stage 1 - add nested stack

---

deploy/template.yaml

Stage 2 of 2 for enabling ECS Canaries (Stage 1 is [here](https://github.com/govuk-one-login/ipv-cri-fraud-front/pull/475))
This is a fairly arbitrary change to trigger the deployment process, but removes some now-unused ECS config.
Canary deployments provide extra safety measures when rolling out new application image versions
https://govukverify.atlassian.net/browse/IPS-556
AllAtOnce rollout tested in `-dev`:

IPS-556/fraud ecs canary stage 2

---

package.json
yarn.lock

Updated nyc dependency from version 15.0.1 to 17.0.0
A vulnerability has been discovered in versions of the babel/traverse dependency pre-dating version 7.23.2. Version 15.0.1 of the nyc dependency utilised an insecure version of babel/traverse. No other dependencies were found to contain any problematic versions of babel/traverse.
Updating the nyc dependency to version 17.0.0 has pulled an updated and secure version of babel/traverse. This was discussed with Jamie Bentham.
- [LIME-1224](https://govukverify.atlassian.net/browse/LIME-1224)
LIME FE repos di-ipv-cri-uk-passport-front-v1, di-ipv-cri-dl-front and ipv-cri-kbv-hmrc-front have also been checked for the babel/traverse vulnerability. Only di-ipv-cri-dl-front was found to have an insecure version. Sarah Hill has addressed this and …

LIME-1224 dependency nyc updated to remove babel security issue

---

package.json
src/app.test.js
src/dynamo-session-config.js
yarn.lock

Upgrade aws-sdk V2 to V3 as AWS SDK for JavaScript v2 will enter maintenance mode on September 8, 2024.
Upgraded aws-sdk in package.json with V3. 
Dynamo session config and app.test were updated to reflect the V3 format
Upgraded to V3 format
- [LIME-1192](https://govukverify.atlassian.net/browse/LIME-1192)
There may be dependencies that use aws-sdk v2 as a transitive dependency. 
[LIME-1192]: https://govukverify.atlassian.net/browse/LIME-1192?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[LIME-1192] Upgrade to aws-sdk V3

---

.github/workflows/checks.yml
.github/workflows/post-merge-to-build.yml
.github/workflows/post-merge-to-dev.yml
.pre-commit-config.yaml
deploy/template.yaml

- Add SAM validate on pre-merge checks and lint on the pre and post merge checks
- Ran `pre-commit autoupdate`
The following change was required to pass the new linting steps:
1. Create condition for `HealthCheckGracePeriodSeconds` (this Property is only used if canaries are disabled ie if the service is using a load balancer and not managed by CodeDeploy). This was to fix `E3056 | ECS service using HealthCheckGracePeriodSeconds must also have LoadBalancers specified` [E3056](https://github.com/aws-cloudformation/cfn-lint/blob/main/src/cfnlint/rules/resources/ecs/ServiceHealthCheckGracePeriodSeconds.py) See the docs at:
- https://docs.aws.amazon.com/AmazonECS/latest/developerguide/service_definition_parameters.html
- https://govukverify.atlassian.net/wiki/spaces/PLAT/pages/3821732161/ECS+- …

IPS-1132: Add linting

---

package.json

hmpo-components updated to v7.1.0. This was previously a breaking update in passport and DL FEs due to a .prefix box appearing in every input field in the browser. Fraud does not have any input fields however checks have been completed to confirm this update will not cause any other issues. 
To facilitate update to v7.1.0
- [LIME-1480](https://govukverify.atlassian.net/browse/LIME-1480)
Same update and workarounds being implemented in Passport and DL FEs.
Evidence on ticket
[LIME-1480]: https://govukverify.atlassian.net/browse/LIME-1480?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1480 hmpo-components updated to 7.1.0

---

.pre-commit-config.yaml
eslint.config.mjs
package.json
test/browser/step_definitions/errors.js
test/browser/step_definitions/fraud.js
test/browser/support/setup.js
yarn.lock

This PR contains a new step in the tests. Upon each page loaded: Fraud Check Page. The Axe Accessibility Script will execute against the 'wcg2aa' (WCGA 2.2 AA) ruleset. And report out any violations as warnings.
- [LIME-1514](https://govukverify.atlassian.net/browse/LIME-1514)
All Tests passed locally, no WCGA 2.2 violations detected
[LIME-1514]: https://govukverify.atlassian.net/browse/LIME-1514?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1514: Added Axe Accessibility Script to run on page load

---

.github/dependabot.yml

Changes made to update dependabot open PR limit to 20 due to present limit of 5 being too few given some PRs can be blocked for some time. 
This FE repo has no dependencies that require grouping so no update made regarding grouping dependencies. 
- [LIME-1229](https://govukverify.atlassian.net/browse/LIME-1229)
[LIME-1229]: https://govukverify.atlassian.net/browse/LIME-1229?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1229 updates Dependabot open PR limit

---

src/app-setup.js
src/app-setup.test.js
src/app.js

Add SIGTERM shutdown, and adjust keepalivetimeout duration to longer than loadbalancer timeout
To implement gracefull shutdown and avoid mismatch between loadbalancer timeout and keepalive.
- [LIME-1352](https://govukverify.atlassian.net/browse/LIME-1352)
- https://govukverify.atlassian.net/browse/DCP-4450
- https://github.com/govuk-one-login/ipv-cri-address-front/pull/1084
- https://github.com/govuk-one-login/ipv-cri-common-express/pull/474
[LIME-1352]: https://govukverify.atlassian.net/browse/LIME-1352?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1352 Add SIGTERM shutdown, and adjust keepalivetimeout duration to longer than loadbalancer timeout (DCP-4450)

---

src/locales/en/default.yml

The aria-label for the language toggle when /check page is in English should also be in English so that English speaking screenreader users receive instructions in a language they understand.
Updated aria-label in english locale file
- [LIME-1510](https://govukverify.atlassian.net/browse/LIME-1510)
[LIME-1510]: https://govukverify.atlassian.net/browse/LIME-1510?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1510 Language Toggle: Updated aria-label

---

.github/workflows/checks.yml

Updated the sonarcube action
The existing action is deprecated and due for removal in March
- [IPS-1428](https://govukverify.atlassian.net/browse/IPS-1428)
[IPS-1428]: https://govukverify.atlassian.net/browse/IPS-1428?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IPS-1428 update sonarcloud version before march deadline

---

package.json
test/browser/features/fraud.feature
test/browser/pages/check.js
test/browser/step_definitions/fraud.js

Added new AC Test to check for device Intelligence cookie and that it has a value
New AC Test Added to fraud.feature
To check that the new device intelligence cookie has been loaded correctly after Fraud Check Page load
- [LIME-1641](https://govukverify.atlassian.net/browse/LIME-1641)
[LIME-1641]: https://govukverify.atlassian.net/browse/LIME-1641?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1641 Add Device Intelligence AC Tests to check for Cookie

---

package.json
test/browser/features/errors-check.feature
test/browser/features/errors-session.feature
test/browser/features/fraud.feature
test/browser/step_definitions/errors.js
test/browser/step_definitions/fraud.js
yarn.lock

Updated Axe Accessibility Tests:
Removed the Axe Scan from the background step of the Scenarios and within Error Page Step Added Specific Test for Passport Details Page and Passport Error Page which runs the Axe Scan
This will allow for clearer reporting and troubleshooting of any accessibility issues going forward
- [LIME-1637](https://govukverify.atlassian.net/browse/LIME-1637)
Test Evidence: 
[LIME-1637]: https://govukverify.atlassian.net/browse/LIME-1637?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1637 - Fraud FE - Split out Axe Scan into Specific Tests for better visibility

---

package.json
test/browser/pages/relying-party.js
test/mocks/mappings/fraud-check-error.json
test/mocks/mappings/fraud-slow.json
test/mocks/mappings/fraud.json
yarn.lock

Yarn.lock removed and re-created to pull in changes from transitive dependency frontend-ui through common-express.  
To bring in the fix to increase the footer font size to 16px.
- [LIME-1770](https://govukverify.atlassian.net/browse/LIME-1770)
[LIME-1770]: https://govukverify.atlassian.net/browse/LIME-1770?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1770 - yarn.lock updated to pull in frontend-ui update
