package.json, yarn.lock
Husky is failing in the build pipeline for some reason, and the version in `fraud` is earlier than the working version in `kbv`.
Updating it to see if this fixes the pipeline issues.
=> chore: Update Husky to v8

package.json, yarn.lock
Use wiremock as a dev dependency, not a production one.
=> chore: Move wiremock to devDependencies

src/views/fraud/check.html
Adding missing privacy notice link
=> KBV-496: Adding missing privacy notice link

src/views/errors/error.html
Fixed styling on contact us link
=> KBV-494: Fixed styling on contact us link

src/app.js, src/app/return-to-dbs.js, src/assets/scss/application.scss, src/assets/scss/spinner.scss, src/locales/en/default.yml, src/locales/en/pages.yml, src/views/return-to-dbs/_banner.html, src/views/return-to-dbs/_base.html, src/views/return-to-dbs/dbs-service.html, src/views/return-to-dbs/page-ipv-success.html, src/views/return-to-dbs/prove-identity-check.html
testing
Accessibility testing the final few pages of the complete journey is really tricky as it requires successful navigating of multiple credential issuers with a successful result. 
To more easily enable this testing, the final three pages have been implemented inside the least complex CRI - the Fraud CRI. 
I've tried to isolate the changes as compactly as possible, to avoid any interference with the actual functioning of the CRI. 
They will be removed once the accessibility testing has finished.
=> feat: Temporarily replicate end of journey to help with accessibility

deploy/template.yaml
Use custom DNS for api backend
Instead of apigatewayID url, use custom DNS
TODO: set a condition for production to not include the environment, use apigatewayID in dev
=> BAU: use custom dns for API_BASE_URL

deploy/template.yaml
=> BAU: fix custom dns for API_BASE_URL

deploy/template.yaml
frontend to use backend private gateway ID instead of custom dns
=> Change FE to use private api gateway id

src/app.js, src/locales/en/default.yml, src/views/errors/error.html, src/views/errors/page-not-found.html, src/views/errors/session-ended.html, src/views/fraud.html, src/views/fraud/check.html, src/views/index.html
Use common page templates in preparation for GTM work
=> Use common templates

src/app.js, test/browser/features/errors-check.feature, test/browser/features/errors-session.feature, test/browser/features/fraud.feature, test/browser/pages/relying-party.js, test/browser/step_definitions/details.js, test/browser/step_definitions/relying-party.js, test/mocks/mappings/fraud-check-error.json, test/mocks/mappings/fraud-session-error.json
Add support for `common-express` error redirecting to keep `fraud` in sync with the changes in `kbv` and `address`
Also, the mocks for `session-error` and `check-error` were in the wrong files, so this has been fixed.
=> feat: Add error redirecting from common-express

src/views/fraud/check.html, test/browser/pages/check.js
When the cookie banner was added into the app, there are now 3 buttons on a page, so the simple implementation of "click the first button" to continue no longer works.
This adds a unique id of "continue" to the continue button, and updates the step definition to target the new id.
=> Add id to continue button

src/locales/en/default.yml
Add locales content for cookie banner
=> Update locales with cookie banner

package.json, src/app.js, yarn.lock
Use Helmet config to provide a default set of security headers.
This is dependent on https://github.com/alphagov/di-ipv-cri-common-express/pull/55 being merged and released.
- [KBV-562](https://govukverify.atlassian.net/browse/KBV-562)
=> Use helmet

deploy/template.yaml
=> Align healthcheck with other CRIs

deploy/template.yaml
Create new DynamoDB table to store the front-end session data.
Bring in line with rest of the programme for front-end sessions storage and means we don't need to manage a redis cluster instance.
- [KBV-609](https://govukverify.atlassian.net/browse/KBV-609)
=> BAU: Create address front-end dynamodb sessions store table and add ECSTaskRole policy

src/locales/en/pages.yml, src/views/fraud/check.html
=> Content: Update content to align with content changes

deploy/template.yaml
Added subscription filter for frontend logs
It did not previously export to splunk
- [KBV-569](https://govukverify.atlassian.net/browse/KBV-569)
=> KBV-569: Added log subscription filter for frontend logs

src/locales/en/pages.yml
Fraud Error page title fix
error page title was incorrect
=> KBV-495 - Fixing Fraud error page title

src/app.js, src/lib/config.js
feat: set session to two hours
- [KBV-683](https://govukverify.atlassian.net/browse/KBV-683)
=> KBV-683-ensure-two-hour-timeout

src/views/fraud/check.html
Add govuk-heading-l style to <h1>
- [KBV-686](https://govukverify.atlassian.net/browse/KBV-686)
=> Add govuk-heading-l style to <h1>

src/locales/en/default.yml
Update link to the cookie policy
- [KBV-670](https://govukverify.atlassian.net/browse/KBV-670)
- https://github.com/alphagov/di-ipv-cri-common-express/pull/72 - this needs to be merged and released as well
=> feat: Change link to account.gov.uk cookie policy

.husky/pre-commit, .secrets.baseline, package.json, yarn.lock
Add a precommit check for secrets 
See OJ-926 on other repos 
=> OJ 926 add security pre-commit hook

package.json
Allow any 16.x version of node to avoid package installation errors.
=> chore: Allow any 16.x version of node

src/locales/en/pages.yml, src/views/fraud/check.html
Extract content into locales files.
- [OJ-914](https://govukverify.atlassian.net/browse/OJ-914)
=> refactor: Extract content into locales files

.github/workflows/checks.yml, .github/workflows/i18n.yml, package.json
Add `check-translation` script from `common-express` as GHA.
This is a separate non-blocking check that compares the Welsh and English translation files for missing details.
- [OJ-863](https://govukverify.atlassian.net/browse/OJ-863)
=> Oj 863/add check translation gha

src/locales/cy/default.yml, src/locales/cy/pages.errors.yml, src/locales/cy/pages.yml, src/locales/en/default.yml
Add Welsh translations.
- [OJ-914](https://govukverify.atlassian.net/browse/OJ-914)
=> Oj 914/update locales

deploy/template.yaml
Add new csls log subscription endpoints
To enable logging in splunk after existing endpoints are turned off
- [LIME-190](https://govukverify.atlassian.net/browse/LIME-190)
=> LIME-190: Added new csl python log subscriptions

deploy/template.yaml
Updated task count and scaling targets
To align with the other CRI products
=> LIME-191: Aligning task counts with other CRIs

.github/workflows/post-merge-to-dev.yml
Added manual dispatch to deploy to dev job
To allow manual triggering of jobs
=> LIME-405: Added manual dispatch to dev deploy job

src/locales/cy/default.yml, src/locales/cy/pages.errors.yml, src/locales/en/default.yml, src/locales/en/pages.errors.yml
This PR updates all content related to the One Login name change
=> DO NOT MERGE: LIME-404 UI One Login content updates

package.json
Bumped common express version
To keep inline with other CRIs
=> Updating common express version

deploy/template.yaml
sizing of deployment infrastructure in the cfn template
Updating build configuration to match production for the performance testing 
- [LIME-698](https://govukverify.atlassian.net/browse/LIME-698)
[LIME-698]: https://govukverify.atlassian.net/browse/LIME-698?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> lime-698 update scaling for performance testing

sonar-project.properties
IPS-310 Sonarcloud Migration
IPS-310 Sonarcloud Migration
- [IPS-310](https://govukverify.atlassian.net/browse/IPS-310)
[IPS-310]: https://govukverify.atlassian.net/browse/IPS-310?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> IPS-310 Sonarcloud Migration to govuk-one-login

.github/workflows/post-merge-to-build.yml, .github/workflows/post-merge-to-dev.yml, CODEOWNERS, Dockerfile, deploy/template.yaml
IPS-300 Fraud ECS dynatrace integration 
IPS-300 Fraud ECS dynatrace integration 
- [IPS-300](https://govukverify.atlassian.net/browse/IPS-300)
[IPS-300]: https://govukverify.atlassian.net/browse/IPS-300?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PS-300 Fraud ECS dynatrace integration 

deploy/template.yaml
Align task scaling with DLFront/CoreFront/AddressFront configurations.
Align FraudAPI with DL Front values
- [LIME-727](https://govukverify.atlassian.net/browse/LIME-727)
[LIME-727]: https://govukverify.atlassian.net/browse/LIME-727?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-727 Align task scaling with DL-front

.github/workflows/checks.yml, sonar-project.properties
Updating coverage reports for fraud front
To test the sonar integration
Updated sonar token in secrets
=> LIME-000: Testing code coverage in sonar for fraud front

sonar-project.properties
Fixing exclusions in fraud
To allow test coverage to appear in sonar
=> LIME-000: Removing some exclusions

package.json, src/app.js, src/app/fraud/controllers/check.js, src/app/fraud/controllers/check.test.js, src/app/fraud/featureSets.js, src/app/fraud/featureSets.test.js, test/utils/mocha-helpers.js
Added feature set functionality so headers can be dynamically added to requests
To allow testing of new features in higher environments
=> LIME-921: Adding functionality for feature sets so that crosscore v2 can be toggled on

.github/dependabot.yml, .github/workflows/checks.yml, .github/workflows/codeql.yml, .github/workflows/i18n.yml, .github/workflows/post-merge-to-build.yml, .github/workflows/post-merge-to-dev.yml
Update workflows to:
* remove deprecations
* implement dev-platform actions
* prepare for canary deployments
The github workflows
* remove deprecations
* implement dev-platform actions
* prepare for canary deployments
- [IPS-447](https://govukverify.atlassian.net/browse/IPS-447)
- [IPS-480](https://govukverify.atlassian.net/browse/IPS-480)
- [IPS-503](https://govukverify.atlassian.net/browse/IPS-503)
- [IPS-532](https://govukverify.atlassian.net/browse/IPS-532)
- 
[IPS-447]: https://govukverify.atlassian.net/browse/IPS-447?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[IPS-480]: https://govukverify.atlassian.net/browse/IPS-480?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[IPS-503]: …
=> IPS-477 fix workflow warnings

src/locales/cy/pages.yml, src/locales/en/pages.yml, src/views/fraud/check.html, test/browser/features/fraud.feature, test/browser/pages/check.js, test/browser/step_definitions/fraud.js
Adding text to warn users not to refresh page
To reduce errors on fraud CRI
- [LIME-999](https://govukverify.atlassian.net/browse/LIME-999)
[LIME-999]: https://govukverify.atlassian.net/browse/LIME-999?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-999 adding RefreshWarning text

deploy/template.yaml
Enabling welsh toggle in production and integration for the Fraud CRI
=> LIME-1176: Enabling welsh toggle in production and integration

.github/workflows/checks.yml, .pre-commit-config.yaml, .secrets.baseline, README.md
- Added pre-commit GHA workflow step
- Updated pre-commit-config with `detect-secrets`
- Updated secrets.baseline to use "--slim"  format (excludes line numbers and timestamp) to reduce noise and conflicts See https://gds.slack.com/archives/C0222KXB6RM/p1717753820719119
- As per ticket requirements
- [IPS-484](https://govukverify.atlassian.net/browse/IPS-484)
[IPS-484]: https://govukverify.atlassian.net/browse/IPS-484?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> IPS-487: Add pre-commit GHA workflow and update pre-commit-config

.github/workflows/post-merge-to-build.yml, .github/workflows/post-merge-to-dev.yml
Updated upload actions ECR version from 1.2.4 to 1.2.6
- [LIME-XXXX](https://govukverify.atlassian.net/browse/LIME-XXXX)
=> IPS-809 - Updated upload actions ecr versions

src/views/errors/error.html, src/views/errors/page-not-found.html, src/views/errors/session-ended.html, src/views/fraud/check.html
Taxonomy Level 1 value for all pages updated from "cri" to "web cri" as requested by the Data & Analytics team
As part of the CI changes following GA4 go live
(DFC-640)[https://govukverify.atlassian.net/browse/DFC-640]
=> DFC-640 | GA4| Update taxonomy level1 for pageViewTracker

package.json, yarn.lock
Reverts hmpo-components update from 6.3.0 to 7.1.0 due to breaking change when dependency merged
=> Reverts hmpo-components update from 6.3.0 to 7.1.0

.secrets.baseline, Dockerfile, deploy/template.yaml, yarn.lock
Healthcheck configured and Dockerfile command amended to create unique DYNATRACE_HOST_ID value for different containers. 
The healthcheck ensures fast failure if containers are taking to long to respond. Having unique DYNATRACE_HOST_ID values allows for monitoring of different containers. 
- [LIME-1345](https://govukverify.atlassian.net/browse/LIME-1345)
- [LIME-1351](https://govukverify.atlassian.net/browse/LIME-1351)
Same amendments made to DL and Passport.
- Successful user journey carried out locally 
- FE unit tests and feature tests passing:
- BE UI Feature tests passing (@stub tests in dev environment):
- Confirmed fraud /healthcheck route working:
- Confirmed fraud healthcheck task works:
[LIME-1345]: https://govukverify.atlassian.net/browse/LIME-1345?atlOrigin=eyJpIjoiNWRkNTljNzYx …
=> LIME-1345 healthcheck configured

package.json, src/app/fraud/overloadProtection.js, src/app/fraud/overloadProtection.test.js, src/router.js
Added FrontEnd Vital signs logging metrics
=> LIME-1343 - Implementing Overload Protection/Adding Vital signs logging

package.json, src/app.js
- [LIME-XXXX](https://govukverify.atlassian.net/browse/LIME-XXXX)
=> LIME-1512 Common Express updated with cookie banner fix

Dockerfile
=> LIME-1351 - Fixing host name

test/browser/features/WelshLangFraudCRI.feature, test/browser/features/errors-check.feature, test/browser/features/errors-session.feature, test/browser/features/fraud.feature, test/browser/pages/check.js, test/browser/step_definitions/details.js, test/browser/step_definitions/fraud.js, test/browser/step_definitions/relying-party.js
Tests have been updated to reduce number of steps
Method for validating the ThirdParty and PrivacyPolicy Links updated for better stability
Tests have been updated to reduce number of steps
Method for validating the ThirdParty and PrivacyPolicy Links updated for better stability
To provide better stability when tests are running as part of the pre-merge checks
To improve the readability of the test steps
- [LIME-1004](https://govukverify.atlassian.net/browse/LIME-1004)
[LIME-1004]: https://govukverify.atlassian.net/browse/LIME-1004?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-1004 - Update FE Step Definitions for better readability

.secrets.baseline, deploy/template.yaml
Make NODE_ENV settings consistent across different environments.
Added NODE_ENV mapping to template.
- [LIME-1604](https://govukverify.atlassian.net/browse/LIME-1604)
[LIME-1604]: https://govukverify.atlassian.net/browse/LIME-1604?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME_1604 Standardised NODE_ENV Configuration for Fraud

deploy/template.yaml
Toggle Device Intelligence to true in Staging-Production
To Enable Device Intelligence Staging-Production
- [LIME-1636](https://govukverify.atlassian.net/browse/LIME-1636)
[LIME-1636]: https://govukverify.atlassian.net/browse/LIME-1636?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-1636 Enable Device Intelligence Staging-Production

package.json, yarn.lock
Upgrade Axios and Waiton
Resolve transitive dependency issues
- [LIME-1775](https://govukverify.atlassian.net/browse/LIME-1775)
[LIME-1775]: https://govukverify.atlassian.net/browse/LIME-1775?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-1775 Upgrade axios and waiton

package.json, yarn.lock
Updating @cucumber/cucumber version to 11.3.0.
- [LIME-1799](https://govukverify.atlassian.net/browse/LIME-1799)
[LIME-1799]: https://govukverify.atlassian.net/browse/LIME-1799?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-1799: Updating @cucumber/cucumber version.
